Questions done : 13, 16, 17, 30, 29, 15, 18, 19, 20 ,24

In [ ]:
# Ques 13

# "The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 
# 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?"
import math
def count_divisors(num):
    count = 0
    sqrt = int(math.sqrt(num))
    for i in range(1, sqrt+1):
        if num % i == 0:
            count += 2
    if sqrt * sqrt == num:
        count -= 1
    return count

def first_triangle_number(n):
    num = 1
    triangle_number = 1
    while True:
        if count_divisors(triangle_number) > n:
            return triangle_number
        num += 1
        triangle_number+=num


print(first_triangle_number(500))

76576500

In [ ]:
##Ques 16
# "2^15 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.
# What is the sum of the digits of the number 21000?"

def sum_of_digts(n):
    sum = 0
    for digits in str(n):
        sum += int(digits)
    return sum

print(sum_of_digts(2**1000))

1366

In [ ]:
#QUES 17
# "If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.
# If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?

# NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) 
# contains 20 letters. The use of ""and"" when writing out numbers is in compliance with British usage."

def number_to_words(n):
    
    ones = ["", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", 
            "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", 
            "seventeen", "eighteen", "nineteen"]
    
    tens = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]
    
    if 1 <= n < 20:
        return ones[n]
    
    elif 20 <= n < 100:
        return tens[n // 10] + (ones[n % 10] if n % 10 != 0 else "")
    
    elif 100 <= n < 1000:
        return ones[n // 100] + "hundred" + (("and" + number_to_words(n % 100)) if n % 100 != 0 else "")
    
    elif n == 1000:
        return "onethousand"
    
    return "" 

def total_letter_count(limit):
    """Compute the total letter count from 1 to 'limit' when written in words."""
    total = 0
    for i in range(1, limit + 1):  
        total += len(number_to_words(i))  
    return total  

# Compute letter count for numbers from 1 to 1000
print(total_letter_count(1000))  # Expected output: 21124

21124

In [4]:
#QUES 30 :  "Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
# 22=4, 23=8, 24=16, 25=32
# 32=9, 33=27, 34=81, 35=243
# 42=16, 43=64, 44=256, 45=1024
# 52=25, 53=125, 54=625, 55=3125
# If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
# 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?"


def distinct_powers():
    terms = set()
    for a in range(2, 6):
        for b in range(2, 6):
            terms.add(a ** b)
    return len(terms)

print(distinct_powers())

15

In [ ]:
#QUES 29: "Starting with the number 1 and moving to the right in a clockwise direction a 5 by 5 spiral is formed as follows:
# 21 22 23 24 25
# 20  7  8  9 10
# 19  6  1  2 11
# 18  5  4  3 12
# 17 16 15 14 13
# It can be verified that the sum of the numbers on the diagonals is 101.
# What is the sum of the numbers on the diagonals in a 1001 by 1001 spiral formed in the same way?"

def diagonal_sum(spiral_size):
    total_sum = 1  # Start with the center value
    for n in range(3, spiral_size + 1, 2):  # Odd numbers only
        total_sum += 4 * n * n - 6 * (n - 1)
    return total_sum

print(diagonal_sum(1001))

669171001

In [1]:
# QUES 15:"The following iterative sequence is defined for the set of positive integers:
# n → n/2 (n is even)
# n → 3n + 1 (n is odd)
# Using the rule above and starting with 13, we generate the following sequence:
# 13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1
# It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.
# Which starting number, under one million, produces the longest chain?
# NOTE: Once the chain starts the terms are allowed to go above one million."


def collatz_sequence_length(n, memo):
    if n in memo:
        return memo[n]
    
    if n == 1:
        return 1
    
    if n % 2 == 0:
        next_n = n // 2
    else:
        next_n = 3 * n + 1
    
    memo[n] = 1 + collatz_sequence_length(next_n, memo)
    return memo[n]

def longest_collatz(limit):
    memo = {}
    max_length = 0
    starting_number = 0

    for i in range(1, limit):
        length = collatz_sequence_length(i, memo)
        if length > max_length:
            max_length = length
            starting_number = i

    return starting_number, max_length

# Finding the longest chain for numbers under one million
limit = 1000000
result = longest_collatz(limit)
print(f"The starting number under {limit} that produces the longest chain is {result[0]} with a length of {result[1]}.")

The starting number under 1000000 that produces the longest chain is 837799 with a length of 525.

In [ ]:
# # QUES 18 : "By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.
# 3
# 7 4
# 2 4 6
# 8 5 9 3
# That is, 3 + 7 + 4 + 9 = 23.
# Find the maximum total from top to bottom of the triangle below:
# 75
# 95 64
# 17 47 82
# 18 35 87 10
# 20 04 82 47 65
# 19 01 23 75 03 34
# 88 02 77 73 07 63 67
# 99 65 04 28 06 16 70 92
# 41 41 26 56 83 40 80 70 33
# 41 48 72 33 47 32 37 16 94 29
# 53 71 44 65 25 43 91 52 97 51 14
# 70 11 33 28 77 73 17 78 39 68 17 57
# 91 71 52 38 17 14 91 43 58 50 27 29 48
# 63 66 04 68 89 53 67 30 73 16 69 87 40 31
# 04 62 98 27 23 09 70 98 73 93 38 53 60 04 23
# NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge 
# with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)"


triangle = [
    [75],
    [95, 64],
    [17, 47, 82],
    [18, 35, 87, 10],
    [20, 4, 82, 47, 65],
    [19, 1, 23, 75, 3, 34],
    [88, 2, 77, 73, 7, 63, 67],
    [99, 65, 4, 28, 6, 16, 70, 92],
    [41, 41, 26, 56, 83, 40, 80, 70, 33],
    [41, 48, 72, 33, 47, 32, 37, 16, 94, 29],
    [53, 71, 44, 65, 25, 43, 91, 52, 97, 51, 14],
    [70, 11, 33, 28, 77, 73, 17, 78, 39, 68, 17, 57],
    [91, 71, 52, 38, 17, 14, 91, 43, 58, 50, 27, 29, 48],
    [63, 66, 4, 68, 89, 53, 67, 30, 73, 16, 69, 87, 40, 31],
    [4, 62, 98, 27, 23, 9, 70, 98, 73, 93, 38, 53, 60, 4, 23]
]
# triangle = [
#     [3],
#     [7, 4],
#     [2, 4, 6],
#     [8, 5, 9, 3]
# ]

# Start from the second-last row and move upwards
for row in range(len(triangle) - 2, -1, -1):
    for col in range(len(triangle[row])):
        # Update the current element to be the max path sum
        triangle[row][col] += max(triangle[row+1][col], triangle[row+1][col+1])

# The maximum sum is now in the top element
print(f"Maximum total from top to bottom: {triangle[0][0]}")

Maximum total from top to bottom: 23

In [4]:
# QUES 19 : "You are given the following information, but you may prefer to do some research for yourself.
# 1 Jan 1900 was a Monday.
# Thirty days has September,
# April, June and November.
# All the rest have thirty-one,
# Saving February alone,
# Which has twenty-eight, rain or shine.
# And on leap years, twenty-nine.
# A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.
# How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?"


def count_sundays():
    days_in_months = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    day_of_week = 1  # 1 Jan 1900 was Monday, so 1 Jan 1901 is Tuesday (since 1900 had 365 days)
    sunday_count = 0

    for year in range(1901, 2001):
        for month in range(12):
            if day_of_week == 0:  # 0 represents Sunday
                sunday_count += 1

            # Calculate days in the current month
            if month == 1:  # February
                if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):  # Leap year
                    days_in_month = 29
                else:
                    days_in_month = 28
            else:
                days_in_month = days_in_months[month]

            # Move to the first day of the next month
            day_of_week = (day_of_week + days_in_month) % 7

    return sunday_count

print(f"Number of Sundays on the first of the month: {count_sundays()}")

Number of Sundays on the first of the month: 172

In [7]:
# QUES 20: "n! means n × (n − 1) × ... × 3 × 2 × 1
# For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
# and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.
# Find the sum of the digits in the number 100!"

import math

def sum_of_digits_in_factorial(n):
    factorial_value = math.factorial(n)  # Compute n!
    return sum(int(digit) for digit in str(factorial_value))  # Sum the digits

print(sum_of_digits_in_factorial(100))

648

In [11]:
# QUES 24: "A permutation is an ordered arrangement of objects. For example, 3124 is one possible permutation of the digits 1, 2, 3 and 4. 
# If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of 0, 1 and 2 are:
# 012   021   102   120   201   210
# What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?"

from math import factorial

def lexicographic_permutation(n, digits):
    """Find the nth lexicographic permutation of given digits."""
    permutation = []
    n -= 1  # Convert to 0-based index

    while digits:
        fact = factorial(len(digits) - 1)
        index = n // fact
        permutation.append(digits.pop(index))
        n %= fact

    return ''.join(map(str, permutation))

# Finding the 1,000,000th lexicographic permutation of digits 0-9
digits = list(range(10))
millionth_permutation = lexicographic_permutation(1000000, digits)
print(millionth_permutation)

2783915460